### ISSUE TITLE
Undefined variable: "$h1"

### ISSUE THREAD

**Issue by abdurahman-harouat** [gethugothemes/bookworm-light-hugo#25]
hello my friend , .. i'm getting this error : 

```bash
Error: Error building site: TOCSS: failed to transform "style.main.scss" (text/x-scss): "/home/$USER/Downloads/quickstart/themes/bookworm-light/assets/scss/_typography.scss:2:15": Undefined variable: "$h1".
```

when running 

```bash 
hugo server -D
```

**Comment by mehedi-sharif** [comment]
Hello @kherwata 

I think you are not using the Hugo_extended version on your machine. that's why the scss cannot be generated ad throwing error. try to install the hugo_extended version.

**Comment by kherwata** [comment]
i'm using Hugo_extended version and still getting the same error

**Comment by mehedi-sharif** [comment]
did you follow those steps:

```
# clone the repository
git clone git@github.com:gethugothemes/bookworm-light.git

# cd in the project directory
$ cd bookworm-light/exampleSite/

# Start local dev server
$ hugo server --themesDir ../..
```

**Comment by sumodirjo** [comment]
I also get similar error message even though I use hugo extended.

Initially I use version 0.99.1 get the similar error.

Upgrading to 0.101.0 still giving same error

Downgrading to 0.97.0 no error

Then I tried to re-install version 0.101.0 no error

Initially I was suspecting problem in newer hugo version but apparently not. Not sure yet what was causing the error.

**Comment by vinnu23** [comment]
I had the issues but it worked after I copied the config.toml file from the example site to the current config.toml

**Comment by Herndl** [comment]
I removed the following lines from the config.toml to resolve the error:

```
############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.87.0"
```

**Comment by tfsomrat** [comment]
Use the latest version of Hugo to fix this error. thanks
