### ISSUE TITLE
Floating ToC Support

### ISSUE THREAD

**Issue by mirceanton** [gethugothemes/bookworm-light-hugo#37]
Currently, there doesn't seem to be a way to add a floating table of contents to the side of a blog post. For longform content, it can make reading the post easier.

![image](https://github.com/gethugothemes/bookworm-light-hugo/assets/28601784/6e3d8297-fb3a-4a86-bce4-d1ef0188ffa4)

I think that there should be plenty of room to add one on the side, similar to the red square shown in the image above. On mobile if could be hidden as there isn't that much room available. Maybe the position could be set with a variable as well (either on the left or on the right of the content).

**Comment by tfsomrat** [comment]
Hey @mirceanton, we only use github issues for bugs, if you need any customization, you can take our service from: https://gethugothemes.com/services
