### ISSUE TITLE
How to update the temaplate to use Page Bundles?

### ISSUE THREAD

**Issue by rahulrai-in** [gethugothemes/bookworm-light-hugo#39]
Currently, the template requires images to be placed in the static folder or the assets folder. Can you suggest the modification necessary to enable it to use Page Bundles?

I want to store the blog post and all associated images, including the hero image in the same folder.

**Comment by tfsomrat** [comment]
Hey @rahulrai-in, I am sorry, but I didn't understand what do you mean by page bundles. can you explain, or give me some link to learn more about it?

**Comment by rahulrai-in** [comment]
Apologies @tfsomrat I should have added a link to the feature. Here it is: https://gohugo.io/content-management/page-bundles/

**Comment by rahulrai-in** [comment]
I want to store images of a blog post in the same folder as the blog post. For example, in the following organization (screenshot from the documentation link)

![Screenshot_20240325-210030.png](https://github.com/gethugothemes/bookworm-light-hugo/assets/11886524/bc0bc73f-a126-43cb-a299-1cbeae97f02d)

I'd like to keep the my-post blog post's images: image-1, image-2 etc. in the folder of the blog post.

**Comment by rahulrai-in** [comment]
I have used this style of content organization in my other blog. See this for reference. This doesn't use Page Bundle though. 

https://github.com/rahulrai-in/thecloudblog/tree/master/tcb%2Fcontent%2Fpost%2FAdd%20DevOps%20To%20Your%20Existing%20Dockerized%20Applications%20With%20Azure%20DevOps%20Projects

**Comment by tfsomrat** [comment]
you can use this image partial: https://github.com/gethugothemes/hugo-modules/blob/master/images/layouts/partials/image.html

it has every functionality for loading image from assets/static/content/remote. just read the [docs](https://github.com/gethugothemes/hugo-modules/blob/master/images/README.md#image-implementation) to use it properly.

Or you can hire us to do it for you at https://gethugothemes.com/get-a-quote

**Comment by rahulrai-in** [comment]
I tried editing the partial template. However, for some reason it is not able to fetch Page reaources.

The command `.Page.Resources.Get` return nil in the template.
